version: '3.8'

services:
  icecast:
    image: ghcr.io/laamaa/icecast-alpine:latest
    container_name: icecast-server
    ports:
      - "8000:8000"
    volumes:
      - ./config/icecast.xml:/etc/icecast2/icecast.xml:ro
      - ./logs:/var/log/icecast2
      - ./data:/var/lib/icecast2
    environment:
      - ICECAST_SOURCE_PASSWORD=hackme
      - ICECAST_RELAY_PASSWORD=hackme
      - ICECAST_ADMIN_PASSWORD=hackme
    restart: unless-stopped